project:
  type: website
  output-dir: docs

website:
  title: "Kathleen's Lab Notebook"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shedurkin
      - icon: twitter
        href: https://twitter.com/kmdurkin_dna
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

