project:
  type: website
  output-dir: docs

website:
  title: "Kathleen's Lab Notebook"
  navbar:
    logo: grad_headshot_circlecrop.png
    right:
#      - about.qmd
      - href: projects.qmd
        text: Projects

#      - href: notebook.qmd
#        text: Daily Notebook Posts
        
      - icon: github
        href: https://github.com/shedurkin
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

#margin-header: |
#  ![](grad_headshot_circlecrop.png)
