project:
  type: website
  output-dir: docs

website:
  title: "Kathleen's Lab Notebook"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shedurkin
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

